/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const HomeworkEntry = IDL.Record({
  'title' : IDL.Text,
  'dueDate' : IDL.Text,
  'description' : IDL.Text,
});
export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const Profile = IDL.Record({
  'name' : IDL.Text,
  'role' : IDL.Text,
  'address' : IDL.Text,
  'phone' : IDL.Text,
});
export const Fee = IDL.Record({ 'status' : IDL.Text, 'amount' : IDL.Nat });
export const Message = IDL.Record({
  'content' : IDL.Text,
  'sender' : IDL.Text,
  'recipients' : IDL.Vec(IDL.Text),
  'timestamp' : IDL.Nat,
});

export const idlService = IDL.Service({
  '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
  'addHomework' : IDL.Func([IDL.Text, HomeworkEntry], [], []),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'assignFormTeacher' : IDL.Func([IDL.Text, IDL.Text], [], []),
  'assignTeacherToClass' : IDL.Func([IDL.Text, IDL.Text], [], []),
  'deleteHomework' : IDL.Func([IDL.Text], [], []),
  'getAllProfiles' : IDL.Func([], [IDL.Vec(Profile)], ['query']),
  'getAttendance' : IDL.Func([IDL.Text, IDL.Text], [IDL.Bool], ['query']),
  'getCallerUserProfile' : IDL.Func([], [IDL.Opt(Profile)], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getFees' : IDL.Func([IDL.Text], [IDL.Opt(Fee)], ['query']),
  'getHomework' : IDL.Func([IDL.Text], [IDL.Opt(HomeworkEntry)], ['query']),
  'getMessages' : IDL.Func([], [IDL.Vec(Message)], ['query']),
  'getProfile' : IDL.Func([IDL.Text], [IDL.Opt(Profile)], ['query']),
  'getUserProfile' : IDL.Func([IDL.Text], [IDL.Opt(Profile)], ['query']),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'markAttendance' : IDL.Func([IDL.Text, IDL.Text, IDL.Bool], [], []),
  'saveCallerUserProfile' : IDL.Func([Profile], [], []),
  'sendMessage' : IDL.Func([Message], [], []),
  'undoAttendance' : IDL.Func([IDL.Text, IDL.Text], [], []),
  'undoFee' : IDL.Func([IDL.Text], [], []),
  'undoHomework' : IDL.Func([IDL.Text], [], []),
  'undoProfile' : IDL.Func([IDL.Text], [], []),
  'updateFee' : IDL.Func([IDL.Text, Fee], [], []),
  'updateProfile' : IDL.Func([Profile], [], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const HomeworkEntry = IDL.Record({
    'title' : IDL.Text,
    'dueDate' : IDL.Text,
    'description' : IDL.Text,
  });
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const Profile = IDL.Record({
    'name' : IDL.Text,
    'role' : IDL.Text,
    'address' : IDL.Text,
    'phone' : IDL.Text,
  });
  const Fee = IDL.Record({ 'status' : IDL.Text, 'amount' : IDL.Nat });
  const Message = IDL.Record({
    'content' : IDL.Text,
    'sender' : IDL.Text,
    'recipients' : IDL.Vec(IDL.Text),
    'timestamp' : IDL.Nat,
  });
  
  return IDL.Service({
    '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
    'addHomework' : IDL.Func([IDL.Text, HomeworkEntry], [], []),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'assignFormTeacher' : IDL.Func([IDL.Text, IDL.Text], [], []),
    'assignTeacherToClass' : IDL.Func([IDL.Text, IDL.Text], [], []),
    'deleteHomework' : IDL.Func([IDL.Text], [], []),
    'getAllProfiles' : IDL.Func([], [IDL.Vec(Profile)], ['query']),
    'getAttendance' : IDL.Func([IDL.Text, IDL.Text], [IDL.Bool], ['query']),
    'getCallerUserProfile' : IDL.Func([], [IDL.Opt(Profile)], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getFees' : IDL.Func([IDL.Text], [IDL.Opt(Fee)], ['query']),
    'getHomework' : IDL.Func([IDL.Text], [IDL.Opt(HomeworkEntry)], ['query']),
    'getMessages' : IDL.Func([], [IDL.Vec(Message)], ['query']),
    'getProfile' : IDL.Func([IDL.Text], [IDL.Opt(Profile)], ['query']),
    'getUserProfile' : IDL.Func([IDL.Text], [IDL.Opt(Profile)], ['query']),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'markAttendance' : IDL.Func([IDL.Text, IDL.Text, IDL.Bool], [], []),
    'saveCallerUserProfile' : IDL.Func([Profile], [], []),
    'sendMessage' : IDL.Func([Message], [], []),
    'undoAttendance' : IDL.Func([IDL.Text, IDL.Text], [], []),
    'undoFee' : IDL.Func([IDL.Text], [], []),
    'undoHomework' : IDL.Func([IDL.Text], [], []),
    'undoProfile' : IDL.Func([IDL.Text], [], []),
    'updateFee' : IDL.Func([IDL.Text, Fee], [], []),
    'updateProfile' : IDL.Func([Profile], [], []),
  });
};

export const init = ({ IDL }) => { return []; };