/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface Fee { 'status' : string, 'amount' : bigint }
export interface HomeworkEntry {
  'title' : string,
  'dueDate' : string,
  'description' : string,
}
export interface Message {
  'content' : string,
  'sender' : string,
  'recipients' : Array<string>,
  'timestamp' : bigint,
}
export interface Profile {
  'name' : string,
  'role' : string,
  'address' : string,
  'phone' : string,
}
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export interface _SERVICE {
  '_initializeAccessControlWithSecret' : ActorMethod<[string], undefined>,
  'addHomework' : ActorMethod<[string, HomeworkEntry], undefined>,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'assignFormTeacher' : ActorMethod<[string, string], undefined>,
  'assignTeacherToClass' : ActorMethod<[string, string], undefined>,
  'deleteHomework' : ActorMethod<[string], undefined>,
  'getAllProfiles' : ActorMethod<[], Array<Profile>>,
  'getAttendance' : ActorMethod<[string, string], boolean>,
  'getCallerUserProfile' : ActorMethod<[], [] | [Profile]>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'getFees' : ActorMethod<[string], [] | [Fee]>,
  'getHomework' : ActorMethod<[string], [] | [HomeworkEntry]>,
  'getMessages' : ActorMethod<[], Array<Message>>,
  'getProfile' : ActorMethod<[string], [] | [Profile]>,
  'getUserProfile' : ActorMethod<[string], [] | [Profile]>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'markAttendance' : ActorMethod<[string, string, boolean], undefined>,
  'saveCallerUserProfile' : ActorMethod<[Profile], undefined>,
  'sendMessage' : ActorMethod<[Message], undefined>,
  'undoAttendance' : ActorMethod<[string, string], undefined>,
  'undoFee' : ActorMethod<[string], undefined>,
  'undoHomework' : ActorMethod<[string], undefined>,
  'undoProfile' : ActorMethod<[string], undefined>,
  'updateFee' : ActorMethod<[string, Fee], undefined>,
  'updateProfile' : ActorMethod<[Profile], undefined>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];